### ISSUE TITLE
Requesting the addition of a timeout parameter in the api functions

### ISSUE THREAD

**Issue by jedevies** [CDCgov/Rnssp#21]
It would be great if a user could adjust the timeout parameter for Httr GET requests from within the Rnssp api functions like get_api_data.

For example, something like below:

`api_data <- get_api_data("url", timeout = 100)`

**Comment by rosericazondekon** [comment]
Thank you @jedevies  for your contribution.
The timeout argument has been added across to the function and methods accordingly. The enhancements are pushed to the `dev` branch and will be available in the upcoming version `0.3.1`.
