### ISSUE TITLE
Add functionality to return just a data frame rather than a list

### ISSUE THREAD

**Issue by sara-chronister** [CDCgov/Rnssp#4]
Currently the API call functions built into the Rnssp package return a list rather than a data frame (or image). Users are still required to extract the data frame or image from the list for each API call, a step that could be wrapped into the existing API call functions. This would require fewer lines of code for users to write, reduce the chances of error, and make the package and APIs more user-friendly. 

Below is a suggested function that would return the final result from each type of API call (including visualizations). Arguments have been made in the past that if the API structure changes, functions like this would no longer work, but if that does happen then users will have to update all of their code to match the new structure. This way, any updates in the API structure can be accounted for in this function, and as long as users update the package they will be able to use the function to call the API and get the output they need.

The function below is based on the code found in the Rnssp_intro vignette (https://cdcgov.github.io/Rnssp/articles/Rnssp_intro.html) prior to the addition of the newer API call functions.

```r

get_essence_data <- function(url, start_date = NULL, end_date = NULL) {
  
  api_type <- str_extract(url,"(?<=api/).+(?=\\?)")
  
  url_new <- change_dates(url, start_date, end_date)
  
  if (api_type == "timeSeries") {
    api_response <- myProfile$get_api_response(url_new)
    api_response_json <- content(api_response, as = "text")
    api_data <- fromJSON(api_response_json) %>%
      extract2("timeSeriesData")
  } else if (api_type == "timeSeries/graph") {
    api_png <- myProfile$get_api_tsgraph(url_new)
    knitr::include_graphics(api_png$tsgraph)
  } else if (api_type == "tableBuilder") {
    api_data <- myProfile$get_api_data(url_new)
  } else if (api_type == "tableBuilder/csv") {
    api_data <- myProfile$get_api_data(url_new, fromCSV = TRUE)
  } else if (api_type == "dataDetails") {
    api_data <- myProfile$get_api_data(url_new) %>%
      extract2("dataDetails")
  } else if (api_type == "dataDetails/csv") {
    api_data <- myProfile$get_api_data(url_new, fromCSV = TRUE) 
  } else if (api_type == "summaryData") {
    api_data <- myProfile$get_api_data(url_new) %>%
      extract2("summaryData")
  } else if (api_type == "alerts/regionSyndromeAlerts") {
    api_data <- myProfile$get_api_data(url_new) %>%
      extract2("regionSyndromeAlerts")
  } else if (api_type == "alerts/hospitalSyndromeAlerts") {
    api_data <- myProfile$get_api_data(url_new) %>%
      extract2("hospitalSyndromeAlerts")
  } else {
    writeLines("Error: API did not work as expected. Please check your URL, dates, and password before trying again.")
  }
  
}

```

**Comment by rosericazondekon** [comment]
Thank you @sara-chronister for opening a new issue. Your suggestion has been placed on our [project TODO list](https://github.com/CDCgov/Rnssp/projects/1#card-80563836), and will be addressed in the next version of the package.

**Comment by rosericazondekon** [comment]
Dear @sara-chronister, 
An implementation of the function you suggested has been pushed to the [dev branch](https://github.com/CDCgov/Rnssp/tree/dev). Please, check it [here](https://github.com/CDCgov/Rnssp/blob/dev/R/api_utilities.R). Also, feel free to install the version of the package in the [dev branch](https://github.com/CDCgov/Rnssp/tree/dev) (`devtools::install_github("cdcgov/Rnssp@dev")`) in order to test the `get_essence_data()` function you suggested. Depending on the feedback, further improvements and/or testing, we shall determine whether it is worth including this function to the next release of the package.

Thank you for your contribution!
